{% set name = "sissopp" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/{{ name }}_developers/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 2b1ef8b2fbe7e2f72c798bb1c45754b16118e8bf58c05fa796b17a877f2d4e6e

build:
  skip: true  # [win or osx]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - pandas
    - scipy
    - seaborn
    - scikit-learn
    - toml
    - mkl
    - libboost-devel ==1.85
    - libboost-mpi
    - coin-or-utils
    - coin-or-clp
    - nlopt
    - fmt
    - pybind11
    - zlib
  run:
    - python
    - _openmp_mutex
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - matplotlib-base
    - mpich
    - mkl
    - libboost-mpi
    - coin-or-utils
    - coin-or-clp
    - nlopt
    - fmt
    - pybind11
    - zlib

test:
  imports:
    - sissopp
  requires:
    - pip
    - pytest
  source_files:
    - tests/pytest
  commands:
    - pip check
    - pytest tests/pytest/

about:
  home: https://gitlab.com/sissopp_developers/sissopp
  summary: 'C++ Implementation of SISSO with python bindings'
  description: |
    This package provides a C++ implementation of SISSO with built in Python bindings 
    for an efficient python interface.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://sissopp_developers.gitlab.io/sissopp/
  dev_url: https://gitlab.com/sissopp_developers/sissopp

extra:
  recipe-maintainers:
    - ansobolev
    - tpurcell90
