{% set name = "sissopp" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/{{ name }}_developers/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 7e8476aac43132ae98266a684814d863726d9651d659f1ed37d29980e4c938af

build:
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
   - BLAS_LIBRARIES=${CONDA_PREFIX}/lib
  number: 3

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
    - pybind11  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - numpy
    - pandas
    - scipy
    - seaborn
    - scikit-learn
    - toml
    - openblas  # [osx]
    - mkl  # [linux]
    - kokkos
    - libboost-devel ==1.85
    - libboost-mpi
    - coin-or-utils
    - coin-or-clp
    - nlopt
    - fmt
    - pybind11
    - zlib
  run:
    - python
    - llvm-openmp  # [osx]
    - _openmp_mutex  # [linux]
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - matplotlib-base
    - mpich
    - libopenblas  # [osx]
    - mkl  # [linux]
    - libboost-mpi
    - coin-or-utils
    - coin-or-clp
    - nlopt
    - fmt

test:
  imports:
    - sissopp
  requires:
    - pip
    - pytest
  source_files:
    - tests/pytest
  commands:
    - pip check
    - pytest tests/pytest/  # [linux]

about:
  home: https://gitlab.com/sissopp_developers/sissopp
  summary: 'C++ Implementation of SISSO with python bindings'
  description: |
    This package provides a C++ implementation of SISSO with built in Python bindings 
    for an efficient python interface.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://sissopp_developers.gitlab.io/sissopp/
  dev_url: https://gitlab.com/sissopp_developers/sissopp

extra:
  recipe-maintainers:
    - ansobolev
    - tpurcell90
